version: '3'
networks:
    proxy:
        external: true
    backend:
        driver: overlay
services:
    web:
        image: cjpalmer/gitweb:0.2.1
        volumes:
        - /srv/git:/srv/git:ro
        - ./gitweb.conf:/etc/gitweb.conf
        networks:
        - proxy
        - backend
    cgi:
        image: cjpalmer/gitweb-cgi:0.2.1
        environment:
        - BASE_URL=https://git.purplebirdman.com/
        volumes:
        - /srv/git:/srv/git:ro
        - ./gitweb.conf:/etc/gitweb.conf
        networks:
        - backend
