version: '3'
networks:
    proxy:
        external: true
    backend:
        driver: overlay
services:
    web:
        image: cjpalmer/gitweb:0.1.0
        volumes:
        - /srv/git:/srv/git:ro
        - ./gitweb.conf:/etc/gitweb.conf
        networks:
        - proxy
        - backend
    cgi:
        image: cjpalmer/gitweb-cgi:0.1.0
        volumes:
        - /srv/git:/srv/git:ro
        - ./gitweb.conf:/etc/gitweb.conf
        networks:
        - backend
